name: Test

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - '**.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'
          scope: '@scribelabsai'
      - name: Install deps
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build lib and tests
        run: npm run build:lib
      - name: Run tests
        run: npm t
